services:
  goofy-bot:
    image: goofy-bot:latest
    build:
      context: .
      dockerfile: Dockerfile

    container_name: goofy-bot

    env_file:
      - .env

    mem_limit: 150m

    restart: unless-stopped
