services:
  goofy-bot:
    image: goofy-bot:latest
    build:
      context: .
      dockerfile: Dockerfile

    container_name: goofy-bot

    ports:
      - "3000:3000"

    env_file:
      - .env

    extra_hosts:
      - "host.docker.internal:host-gateway"

    mem_limit: 150m

    restart: unless-stopped
